"""alter name table password_hash for hashed_password

Revision ID: 989c2689197b
Revises: 23e8d48e40d3
Create Date: 2026-10-06 21:19:35.720631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '989c2689197b'
down_revision: Union[str, Sequence[str], None] = '23e8d48e40d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               nullable=True)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('users', 'full_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
